### ISSUE TITLE
Create some helper functions for tui

### ISSUE THREAD

**Issue by malaartyom** [rustam2027/RISC-V-Emulator#61]
Need to implement functions `void Interpreter::make_step(std::string command);` and `bool Interpreter::has_lines()`. 
First function takes command for debugger as an argument and make some inner stuff to update state and current line. 
Second method should return true if there is next step and false if previous step was the last. 
Example of usage:
```cpp
while(controller.has_lines()) {
        clean();
        auto line_num = controller.get_line();
        auto state = controller.get_state();
        render(line_num, state);
        
        print("> press N to step in, S to step over, O to step out and q or exit to quit\n");
        std::string command = getline();
        controller.make_step(command);
        
}
```
This example is from method `UI::start()`

**Comment by rustam2027** [comment]
Done
